version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 5000:5000

    volumes:
      - .:/app

    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: maindm
      MYSQL_PORT: 3306

    depends_on:
      - db
  
  db:
    image: mysql:8.0

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: maindm

    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306