version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    command: "python main_flask.py"

    ports:
      - 5000:5000

    volumes:
      - .:/app

    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: maindm
      MYSQL_PORT: 3306

    depends_on:
      - db
    networks:
      main:

  
  queue: # Separate container that will consume the Queue messages from rabbitMQ
    build:
      context: .
      dockerfile: Dockerfile

    command: "python consumer.py"
    
    depends_on:
      - backend
    networks:
      main:
  
  db:
    image: mysql:8.0

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: maindm

    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306

    networks:
      main:


# custom network in order to be able to attache rabbitMQ
# # the network needs to be specified in all services 
networks:
  main:
    name: main_net