version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8000:8000

    volumes:
      - .:/app

    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: admindm
      MYSQL_PORT: 3306

    depends_on:
      - db
  
  db:
    image: mysql:8.0

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: admindm

    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306